"""
Azure Pricing MCP Server Architecture Diagram
Generated by diagram-generator agent
Date: 2025-12-02

Prerequisites:
- pip install diagrams
- Graphviz installed (choco install graphviz / brew install graphviz / apt install graphviz)

Generate PNG: python azure_pricing_mcp.py
"""

from diagrams import Diagram, Cluster, Edge
from diagrams.programming.language import Python
from diagrams.custom import Custom
from diagrams.azure.general import Helpsupport
from diagrams.onprem.vcs import Github
from diagrams.onprem.client import Users
from diagrams.generic.compute import Rack
from diagrams.generic.storage import Storage

# Diagram configuration
graph_attr = {
    "fontsize": "28",
    "bgcolor": "white",
    "pad": "0.5",
    "splines": "spline",
    "nodesep": "0.8",
    "ranksep": "1.2"
}

node_attr = {
    "fontsize": "11"
}

edge_attr = {
    "fontsize": "10"
}

with Diagram(
    "Azure Pricing MCP Server\nIntegrated with GitHub Copilot Agents",
    show=False,
    direction="TB",
    filename="azure_pricing_mcp_architecture",
    graph_attr=graph_attr,
    node_attr=node_attr,
    edge_attr=edge_attr,
    outformat="png"
):
    # User interaction
    user = Users("Developer\n(VS Code)")

    # GitHub Copilot Chat
    with Cluster("VS Code Environment"):
        copilot = Github("GitHub Copilot\nChat")

        with Cluster("Custom Agents"):
            architect = Rack("azure-principal\n-architect")
            bicep_plan = Rack("bicep-plan")

    # MCP Layer
    with Cluster("MCP Server Layer"):
        with Cluster("Azure Pricing MCP Server\n(Python 3.10+)"):
            server = Python("server.py\n(MCP Protocol)")
            handlers = Python("handlers.py\n(Tool Implementations)")

            with Cluster("Available Tools (7)"):
                tool_search = Storage("azure_price_search")
                tool_compare = Storage("azure_price_compare")
                tool_estimate = Storage("azure_cost_estimate")
                tool_region = Storage("azure_region_recommend")
                tool_discover = Storage("azure_discover_skus")
                tool_discovery = Storage("azure_sku_discovery")
                tool_discount = Storage("get_customer_discount")

    # External Azure API
    with Cluster("Azure Cloud"):
        azure_api = Helpsupport("Azure Retail\nPrices API\n(Public)")

    # Output artifacts
    with Cluster("Generated Artifacts"):
        cost_doc = Storage("Cost Estimate\nDocumentation\n(.md)")
        waf_report = Storage("WAF Assessment\nwith Pricing")

    # Connections - User to Copilot
    user >> Edge(label="Natural Language\nPricing Query",
                 color="darkgreen") >> copilot

    # Copilot to Agents
    copilot >> Edge(label="Route to\nAgent", color="blue") >> architect
    copilot >> Edge(label="Route to\nAgent", color="blue") >> bicep_plan

    # Agents to MCP Server
    architect >> Edge(label="azure-pricing/*\ntools", color="purple") >> server
    bicep_plan >> Edge(label="azure-pricing/*\ntools",
                       color="purple") >> server

    # Server internal flow
    server >> Edge(color="gray") >> handlers

    # Handlers to Tools
    handlers >> Edge(style="dashed", color="lightgray") >> tool_search
    handlers >> Edge(style="dashed", color="lightgray") >> tool_compare
    handlers >> Edge(style="dashed", color="lightgray") >> tool_estimate
    handlers >> Edge(style="dashed", color="lightgray") >> tool_region
    handlers >> Edge(style="dashed", color="lightgray") >> tool_discover
    handlers >> Edge(style="dashed", color="lightgray") >> tool_discovery
    handlers >> Edge(style="dashed", color="lightgray") >> tool_discount

    # Tools to Azure API
    tool_search >> Edge(label="HTTPS\n(No Auth)", color="orange") >> azure_api
    tool_compare >> Edge(color="orange", style="dashed") >> azure_api
    tool_estimate >> Edge(color="orange", style="dashed") >> azure_api
    tool_region >> Edge(color="orange", style="dashed") >> azure_api
    tool_discover >> Edge(color="orange", style="dashed") >> azure_api
    tool_discovery >> Edge(color="orange", style="dashed") >> azure_api

    # Output generation
    architect >> Edge(label="Generate\nDocs", color="teal") >> cost_doc
    architect >> Edge(label="Include in\nAssessment",
                      color="teal") >> waf_report


if __name__ == "__main__":
    print("Generating Azure Pricing MCP architecture diagram...")
    print("Output: azure_pricing_mcp_architecture.png")
